 DROP TABLE IF EXISTS "student_interest_tags" CASCADE;
 DROP TABLE IF EXISTS "registrations" CASCADE;
 DROP TABLE IF EXISTS "activity_reviews" CASCADE;
 DROP TABLE IF EXISTS "activity_tags" CASCADE;
 DROP TABLE IF EXISTS "tags" CASCADE;
 DROP TABLE IF EXISTS "activity_checkins" CASCADE;
 DROP TABLE IF EXISTS "roles" CASCADE;
 DROP TABLE IF EXISTS "users" CASCADE;
 DROP TABLE IF EXISTS "student_info" CASCADE;
 DROP TABLE IF EXISTS "activities" CASCADE;
 DROP TABLE IF EXISTS "announcements" CASCADE;
 DROP TABLE IF EXISTS "system_logs" CASCADE;
 DROP TABLE IF EXISTS "points_history" CASCADE;

