org: '1359818056'
app: cqnureg
stage: prod
component: http
name: http-flask-zrhUOaPtqx
inputs:
  src:
    hook: pip3 install -r requirements.txt -t ./
    dist: ./
    exclude:
      - .env
      - venv/**
      - venv_new/**
      - instance/**
      - __pycache__/**
      - .git/**
      - .gitignore
      - .DS_Store
  region: ap-chongqing
  faas:
    runtime: Python3.6
    eip: true
    timeout: 60
    memorySize: 512
    tags: []
    framework: flask
    environments:
      - key: ARK_API_KEY
        value: ccde7115-49bc-4977-9e17-e61075fa9eac
      - key: DATABASE_URL
        value: postgresql://cqnureg2_user:Pz8ZVfyLYOD22fkxp9w2XP7B9LsKAPqE@dpg-d1dugl7gi27c73er9p8g-a.oregon-postgres.render.com/cqnureg2
      - key: FLASK_CONFIG
        value: production
    bootstrap:
      cmd: bootstrap.sh 